 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build
       - run: dotnet test --logger "junit;LogFilePath=C:\Users\circleci\project\test-results\junit\results.xml"
       - store_test_results:
            path: C:\Users\circleci\project\test-results\
